routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use Map\Http\Controllers\FrontController;
use Map\Http\Controllers\MapController;
use Map\Http\Controllers\MapCategoryController;
use Map\Http\Controllers\MapTypeController;
use Map\Http\Controllers\MapIconController;
use Map\Http\Controllers\MapSettingsController;
use Map\Http\Controllers\MapZoneController;
use Map\Models\MapSettings;


Route::middleware('web')->group(function (){
   Route::group(['prefix'=>"admin", 'as'=>'admin.', 'middleware' => ['menu.check:1001','is_admin']],static function() {
       Route::get('map', [MapController::class, 'index'])->name('map')->middleware('map_settings');
       Route::group(['prefix' => "map", 'as' => 'map.',], static function () {
           Route::post('zone',[MapZoneController::class,'store']);
           Route::post('zone/{map_zone}',[MapZoneController::class,'update']);
           Route::delete('zone/{map_zone}',[MapZoneController::class,'delete']);
           Route::post('marker/zone/{map_zone}',[MapZoneController::class,'delete_marker']);
           Route::post('/', [MapController::class, 'store'])->name('store')->middleware('map_settings');
           Route::post('/marker/{map_marker}', [MapController::class, 'update'])->name('update')->middleware('map_settings');
           Route::delete('/marker/{map_marker}', [MapController::class, 'destroy'])->name('destroy')->middleware('map_settings');
           Route::resource('category', MapCategoryController::class)->middleware('map_settings');
           Route::resource('type', MapTypeController::class)->middleware('map_settings');
           Route::resource('icon', MapIconController::class)->middleware('map_settings');
           Route::post('order/category',[MapCategoryController::class,'order'])->name('category.order');
           Route::get('publish/category/{map_category}',[MapCategoryController::class,'publish'])->name('category.publish');
           Route::resource('settings', MapSettingsController::class);
       });
   });
    try {
        $settings = MapSettings::first();
        Route::get($settings->seo_url,[FrontController::class,'index'])->name('map.front');
    }catch (Exception $exception){
        
    }
   
});

resources/views/front/index.blade.php
@extends('layouts.inner')
@section('title', $settings->seo_title)
@section('keywords', $settings->seo_keywords)
@section('description', $settings->seo_description)
@section('content')
    @vite('resources/assets/scss/map/map-front.scss')
    <script src="https://api-maps.yandex.ru/v3/?apikey={{ $settings->api_key }}&lang={{ $settings->lang }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/robust-point-in-polygon@1.0.3/robust-pnp.min.js"></script>
    <div class="content">
        <div class="innerPage-header">
            {{-- <x-front.breadcrumbs :breadcrumbs="$bredcrambs" /> --}}
            <div class="container">
                <h1>{!! $settings->title !!}</h1>
            </div>
        </div>
        <section class="map">
            <div class="container">
                <div class="map__wrapper">
                    <div class="map__info container_info"></div>
                    <div class="map__window container_map">
                        <div id="map" style="width: 100%; height: 600px"></div>
                    </div>
                </div>
                <x-map::constructor.mapdata :categories="$categories" />
            </div>
        </section>
    </div>
    <x-map::front.category :categories="$categories" />
    <x-map::front.type :types="$types" />
    <x-map::front.marker />
    <x-map::front.hint />

    <input type="hidden" id="markers" value="{{ $markers }}">
    <input type="hidden" id="settings" value="{{ $settings }}">
    <input type="hidden" id="zone_data" value="{{ $zones }}">
    @vite('resources/js/map/front/index.js')
@endsection

resources/views/map/category/create.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Добавить категорию</h3>

        </div>
        <x-admin.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.catalog.category.store') }}" enctype="multipart/form-data" method="post" class="row row-page-create">
                @csrf
                <div class="tab-content">
                    <x-catalog::create.content />
                    <x-catalog::create.seo />
                    <x-catalog::create.photo />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog.category.index")}}">Список категорий</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавить категорию</li>
        </ol>
    </div>
@endsection

resources/views/map/category/edit.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Редактировать категорию</h3>
        </div>
        <x-admin.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.catalog.category.update',['category'=>$category]) }}" enctype="multipart/form-data" method="post" class="row row-page-create">
                @csrf
                @method('PUT')
                <input type="hidden" value="{{$category->id}}" name="id">
                <div class="tab-content">
                    <x-catalog::edit.content :category="$category" />
                    <x-catalog::edit.seo :category="$category" />
                    <x-catalog::edit.photo :category="$category" />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog.category.index")}}">Список категорий</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать категорию</li>
        </ol>
    </div>
@endsection

resources/views/map/category/index.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <div class="card-body">
            <x-warning />
            <div class="row row-page-create">
                <div class="col-md-8 order-md-first">
                    <div class="dd nestable" id="nestable">
                        <x-map::category.dnd :categories="$categories"/>
                    </div>
                </div>
                <div class="col-md-4">
                    <form action="{{ route('admin.map.category.store') }}" method="POST">
                        @csrf
                        <h4 class="info_title">Добавить категорию</h4>
                        <div class="form-group">
                            <label>Название</label>
                            <input type="text" name="title" class="form-control">
                        </div>
                        <input type="submit" value="Добавить" class="btn btn-success btn-sm">
                    </form>


                </div>
            </div>
        </div>
    </div>
    <input type="hidden" id="route_dd" value="{{  route('admin.map.category.order') }}">
    <script src="{{asset('assets/js/admin/dnd.js')}}" ></script>
    <script src="{{asset('assets/js/admin/delete.js')}}" ></script>
    <script src="{{ asset('assets/js/admin/show.js') }}"></script>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.map")}}">{{ config('map.title') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Список категорий</li>
        </ol>
    </div>
@endsection

resources/views/map/constructor/index.blade.php
@extends('layouts.admin')
@section('title',config('map.title'))
@section('content')
    @vite('resources/assets/scss/map/map-admin.scss')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <div class="card-body d-flex">

            <div style="width: 0px;transition: width 0.5s ease;" class="container_info"></div>
            <div style="width: 100%;transition: width 0.5s ease;" class="container_map">
                <input type="hidden" id="data_second">
                <input type="hidden" id="markers" value="{{ $markers }}">
                <input type="hidden" id="zone_data" value="{{ $zone_data }}">
                <div  id="map" style="width: 100%; height: 600px"></div>
            </div>
        </div>
    </div>

    <script src="https://api-maps.yandex.ru/v3/?apikey={{ $settings->api_key }}&lang={{ $settings->lang }}"></script>
    <script src="https://api-maps.yandex.ru/2.1/?lang={{ $settings->lang }}&amp;apikey={{ $settings->api_key }}" type="text/javascript"></script>
    @vite('resources/js/map/admin/index.js')
    <x-map::constructor.add-position :categories="$categories" :types="$types" />
    <x-map::constructor.category :categories="$categories" />
    <x-map::constructor.type :types="$types" />
    <x-map::constructor.marker  />
    <x-map::constructor.zone  />
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ config('map.title') }}</li>
        </ol>
    </div>
@endsection

resources/views/map/settings/index.blade.php
@extends('layouts.admin')
@section('title',"Настройки")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <x-admin.navigatin-js :links="$settingsLinks" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.map.settings.store') }}" method="POST">
                @csrf
                <x-map::map.settings />
                <input type="submit" value="Сохранить" class="btn btn-sm btn-success">
            </form>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.map")}}">{{ config('map.title') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Настройки</li>
        </ol>
    </div>
@endsection

resources/views/map/type/index.blade.php
@extends('layouts.admin')
@section('title',"Типы")
@section('content')
    <div class="card">
        <x-admin.navigation :links="$links" />
        <x-admin.navigatin-js :links="$typeLinks" />
        <div class="card-body">
            <x-warning />
            <div class="tab-content">

                <x-map::type.type />
                <x-map::type.icons />
{{--            <form action="{{ route('admin.map.settings.store') }}" method="POST">--}}
{{--                @csrf--}}
{{--                <x-map::map.settings />--}}
{{--                <input type="submit" value="Сохранить" class="btn btn-sm btn-success">--}}
{{--            </form>--}}
            </div>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.map")}}">{{ config('map.title') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Типы</li>
        </ol>
    </div>
@endsection